service: github-scraper

plugins:
  - serverless-dotenv-plugin
  - serverless-jest-plugin

provider:
  name: aws
  runtime: nodejs8.10

functions:
  upload:
    handler: src/handlers/upload.upload
    events:
      - http:
          path: /upload
          method: post
          cors: true
          integration: lambda
